import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { Grid, Button } from "@mui/material";
import { useSession, signIn, signOut } from "next-auth/react";

export default function Header() {
    const { data: session } = useSession();
    return (
        <div className={styles.customHeader}>
            <Head>
                <title>dreamhouseai</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Grid className={styles.smallPaddingHorizontal} container>
                <Grid item md={4}>
                    <h3 className={styles.textTitle}>DREAMHOUSE AI</h3>
                </Grid>
                <Grid item md={4}></Grid>
                <Grid item md={4} >
                    {!session ? (
                    <Grid container justifyContent="flex-end">
                        <Button className={styles.boldButton} onClick={() => signIn('google')} variant="contained">Sign in</Button>
                    </Grid>
                    ) : (
                    <Grid container justifyContent="flex-end">
                        <span className={styles.headerText}>Welcome, {session.user.name}</span>
                        <Button onClick={() => signOut()} variant="contained">Sign Out</Button>
                    </Grid>
                    )}  
                </Grid>
            </Grid>
        </div>
    );
}